### ISSUE TITLE
Tracking software changes

### ISSUE THREAD

**Issue by joto** [osmlab/fixing-polygons-in-osm#23]
There is, of course, a lot of software that handles or uses OSM (multi)polygons. This includes, but it not limited to, editors and renderers. Generally all that we are doing here is backwards compatible, so changes in those programs are not strictly necessary, but the goal is to make handling (multi)polygons easier for the software, so we want to tell them about the work here and also get any feedback they might have.

This (meta-)issue is for tracking issues on software that should be aware of the fixing efforts.

# Editors

* [x] iD (openstreetmap/iD#3908)
* [x] JOSM (private conversation with @stoecker)
* [x] Merkaartor (openstreetmap/merkaartor#128)
* [x] Potlatch (https://trac.openstreetmap.org/ticket/5450#ticket)
* [x] Vespucci (MarcusWolschon/osmeditor4android#535)
* [x] ArcGIS OSM Editor (Esri/arcgis-osm-editor#170)

# Data export

* [x] osm2pgsql (openstreetmap/osm2pgsql#580, openstreetmap/osm2pgsql#684)
* [x] imposm (omniscale/imposm3#142)
* [x] osmtogeojson (tyrasd/osmtogeojson#72)

# Libraries

* [x] libosmium

# Other

* [x] Overpass API (drolbr/Overpass-API#380)

Feel free to extend this issue with links to other projects that should be made aware of this effort.

**Comment by nebulon42** [comment]
Regarding Potlatch 2 I don't think this is only a minor issue. The software still creates old-style multipolygons. After my clean-up in Austria I noticed two cases where old-style multipolygons were re-introduced in changesets by P2. E.g. https://www.openstreetmap.org/changeset/46925424 or more specifically https://www.openstreetmap.org/relation/7080945 which was cleaned up already by another user.

Given the position of the software in its life-cycle I think it is unlikely that big changes will happen to it. I don't think this will affect the data on a large scale, but I'm not familiar with the usage stats of P2.

cc @systemed

**Comment by joto** [comment]
I talked with Richard yesterday about P2. He is aware of the problem and might fix this. I suspect, though, he doesn't want to change the behaviour now to support both old and new style. It might make sense to wait a bit and then just support the new (and at that time basically only) style. This suspect this will only be solved really once the main OSM map switches to new-style-only.

**Comment by systemed** [comment]
Yep, pretty much that.

**Comment by stoecker** [comment]
JOSM has a long-standing issue for this: https://josm.openstreetmap.de/ticket/10529 - We already have a expert parameter to disable old style stuff (I did not remember that I added it :-)

**Comment by ImreSamu** [comment]
> Feel free to extend this issue with links to other projects

ArcGIS Editor for OSM:   https://github.com/Esri/arcgis-osm-editor 
    *  Search: [outer way multipolygon](https://github.com/Esri/arcgis-osm-editor/search?utf8=%E2%9C%93&q=outer+way+multipolygon&type=Issues)

**Comment by joto** [comment]
Thanks @ImreSamu . I have opened an issue on their tracker.
